### PR TITLE
UI issue fixed on dashboard

### PR DESCRIPTION
**Pull request by Pallavi-PH**
**Before:**

Screenshot from 2020-01-24 17-10-30

**After:**

Screenshot from 2020-01-24 18-26-26

### CODE REVIEW

**Comment by shiveshabhishek** [comment]
image

I suspect this PR is breaking the other dashboard panels. The panels are getting overlapped over one another.
cc: @avishnu

**Comment by Pallavi-PH** [comment]
This issue was happening because "Total capacity of all clusters" text is lengthier than all other headings. That's why I had defined a fixed height for all the panel-headers. 
Screenshot from 2020-01-24 17-10-30

If this is causing issue with other screens, instead of this approach we can try to vary the width of the `Total capacity of all clusters` panel and decrease any other to compensate.

**Comment by shiveshabhishek** [comment]
Hi @Pallavi-PH, is it possible to directly edit the padding of the container itself and make it give some space to align the `Total capacity of all clusters` in one single line? I just tested this. But not sure if that's the right approach or not.

image

**Comment by Pallavi-PH** [comment]
@shiveshabhishek This will work for this screen size but will face the same issue for smaller screens

**Pull request merged**
